name: atoi_charts
description: atoi charts lib
version: 0.0.1
homepage: https://github.com/EzekR/atoi_charts

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.15.0"
  vector_math: ^2.0.8

flutter:
